# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: bin 的随笔
url: http://0bin.github.io
feed: /atom.xml
author_info: <a href="http://litaotao.github.io/"> bin 的 随 笔 </a>

myblog:
  gavatar: images/bin2.jpg
  gpname: bin
  linkedin: http://www.linkedin.com/in/taotaoli
  github: https://github.com/0bin
  email: mailto:149723722@qq.com
  coverimgs: []
  postbgimg: []

categories: [随笔，books]
